### ISSUE TITLE
gcr-xtrabackup, repository does not exist or may require 'docker login': denied

### ISSUE THREAD

**Issue by luciferhs** [cloudnativeapp/workshop#12]

**Comment by luciferhs** [comment]
Events:
  Type     Reason            Age                    From                     Message
  ----     ------            ----                   ----                     -------
  Warning  FailedScheduling  3m31s (x3 over 3m43s)  default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled         3m27s                  default-scheduler        Successfully assigned monitor/mysqlha-0 to 192.168.81.235
  Normal   Pulling           114s (x4 over 3m25s)   kubelet, 192.168.81.235  Pulling image "registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup:1.0"
  Warning  Failed            114s (x4 over 3m24s)   kubelet, 192.168.81.235  Failed to pull image "registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup:1.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed            114s (x4 over 3m24s)   kubelet, 192.168.81.235  Error: ErrImagePull
  Normal   BackOff           100s (x6 over 3m23s)   kubelet, 192.168.81.235  Back-off pulling image "registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup:1.0"
  Warning  Failed            87s (x7 over 3m23s)    kubelet, 192.168.81.235  Error: ImagePullBackOff
[root@master helm]# helm install mysqlha  mysqlha --namespace monitor


你们不能搞笑啊。

**Comment by resouer** [comment]
> repository does not exist or may require 'docker login'  denied: 

@luciferhs 根据这个 kubelet log，显然，这个错误既可能是由于“镜像不存在”导致的，也可能是“没有权限”导致的（如同你在 issue 里 complain 的点）

这个很容易通过 `docker pull` 就可以验证:

```
$ docker pull registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup:1.0
Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-xtrabackup:1.0 not found
```

看起来是镜像不存在。而这最可能的原因是在 AppHub 后端同步这个镜像的过程中出现了问题，也有可能是这个源镜像突然改名字了，AppHub 还没来得及同步。这个需要工程师 @wonderflow @BH4AWS 在后端具体看下。

任何一个开源项目，都有可能在某个环节出现 BUG 或者意外的情况，情绪化的预设万万要不得。

**Comment by wonderflow** [comment]
我们排查一下，并非有意

**Comment by BH4AWS** [comment]
镜像已经同步，感谢你的及时问题反馈，也帮助我们把事情做得更好。
有问题直接联系我，谢谢。@luciferhs

**Comment by wonderflow** [comment]
感谢反馈
